name: Stuart Mongoose
favicon: null
layout_spectrum: 0.12338104913942516
typography_spectrum: 0.5666924240067601
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.9946289276704192
  lightness: 0.011998338857665658
  saturation: 0.43289173138327897
  rhythmicContrast: 0.9572175308130682
purpose: []
